services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        env_file:
            - .env
        ports:
            - "${API_PORT:-8080}:8080"
        environment:
            - DB_HOST=${DB_HOST:-postgres}
            - DB_PORT=${DB_PORT:-5432}
            - DB_USER=${DB_USER:-postgres}
            - DB_PASSWORD=${DB_PASSWORD:-postgres}
            - DB_NAME=${DB_NAME:-grocery_db}
            - DB_SSLMODE=${DB_SSLMODE:-disable}
            - JWT_SECRET=${JWT_SECRET}
            - JWT_ISSUER=${JWT_ISSUER:-grocery-service}
            - SMS_ENVIRONMENT=${SMS_ENVIRONMENT:-sandbox}
        depends_on:
            postgres:
                condition: service_healthy
        volumes:
            - .:/grocery-service
        networks:
            - grocery-network

    postgres:
        image: postgres:15-alpine
        ports:
            - "${DB_PORT_EXTERNAL:-5433}:5432"
        environment:
            - POSTGRES_USER=${DB_USER:-postgres}
            - POSTGRES_PASSWORD=${DB_PASSWORD:-postgres}
            - POSTGRES_DB=${DB_NAME:-grocery_db}
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - grocery-network
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-postgres}"]
            interval: 5s
            timeout: 5s
            retries: 5

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL:-nehigna@gmail.com}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD:-admin}
        ports:
            - "${PGADMIN_PORT:-5050}:80"
        depends_on:
            - postgres
        networks:
            - grocery-network

volumes:
    postgres_data:

networks:
    grocery-network:
        driver: bridge
