apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-service
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grocery-service
  template:
    metadata:
      labels:
        app: grocery-service
    spec:
      containers:
      - name: grocery-service
        image: grocery-service:latest
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: grocery-config
              key: db_host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: grocery-config
              key: db_port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: grocery-config
              key: db_name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: grocery-secrets
              key: db_user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grocery-secrets
              key: db_password